#!/bin/bash

if [[ $EUID != 0 ]]; then
  exec pkexec "$(realpath $0)" "$USER"
  exit 1
else

file="/etc/gamescope-session-plus/run-commands"

# Use sed to remove lines starting with # and empty lines
sed -e 's/[[:space:]]*#.*// ; /^[[:space:]]*$/d' "$file" |
while read -r line; do
    # Execute each line as a command
    eval "$line" "$@"
done

# Directory containing the .conf files
directory="/etc/gamescope-session-plus/run-commands.d/"

# Loop over each .conf file in the directory
for file in "$directory"*.conf; do
    # Check if the file exists
    if [ -f "$file" ]; then
        # Source the file to execute its contents
        source "$file" "$@"
    else
        echo "File $file does not exist."
    fi
done

fi
